CREATE OR REPLACE VIEW "BREF"."ViewGlobale"
 AS
 SELECT "Individu"."IdIndividu",
    "Individu"."IdEluRNEHisto",
    "Individu"."IdEluSenat",
    "Individu"."IdEluAssemblee",
    "Individu"."NomDeNaissance",
    "Individu"."NomMarital1",
    "Individu"."NomMarital2",
    "Individu"."Prenom",
    "Individu"."Sexe",
    "Individu"."DateNaissance",
    "Individu"."DateDeces",
    "Individu"."Nationalite",
    "Individu"."IdEurope",
    "Individu"."CommuneNaissance",
    "Individu"."DepartementNaissance",
    "Individu"."PaysNaissance",
    "Individu"."Prénom2",
    "Individu"."Prénom3",
    "Individu"."Dit",
    "Individu"."IdPolitiquemania",
    "Mandat"."IdMandat",
    "Mandat"."TypeDuMandat_IdTypeMandat",
    "Mandat"."DateDebutMandat",
    "Mandat"."DateFinMandat",
    "Mandat"."MotifFinMandat",
    "Mandat"."Elu_IdIndividu",
    "Mandat"."NomDUsageIndividu",
    "Mandat"."Territoire_IdTerritoire",
    "Mandat"."IdNuancePolitique",
    "Mandat"."IdProfession",
    "Mandat"."Sources",
    "Mandat"."CorrectionsDate",
    "Mandat"."CorrectionsAutres",
    "Mandat"."Commentaire",
    "Mandat"."IdPartiPolitique",
    "TypeMandat"."IdTypeMandat",
    "TypeMandat"."TypeMandat",
    "ViewFonction"."IdFonction",
    "ViewFonction"."DateDebutFonction",
    "ViewFonction"."DateFinFonction",
    "ViewFonction"."MotifFinFonction",
    "ViewFonction"."TypeDeFonction_IdTypeFonction",
    "ViewFonction"."Fonction_IdMandat",
    "TypeFonction"."IdTypeFonction",
    "TypeFonction"."TypeFonction",
    "Territoire"."IdTerritoire",
    "Territoire"."NomTerritoire",
    "Territoire"."TypeTerritoire",
    "Territoire"."CodeTerritoire",
    "Territoire"."DateLiee",
    "Territoire"."Actif",
    "Inclusion"."IdInclusion",
    "Inclusion"."TerritoireInclu_IdTerritoire",
    "Inclusion"."TerritoireIncluant_IdTerritoire",
    "Inclusion"."DateDebutInclusion",
    "Inclusion"."DateFinInclusion",
    "ViewPopulationCommune"."IdPopulationCommune",
    "ViewPopulationCommune"."Population",
    "ViewPopulationCommune"."DateReference",
    "ViewPopulationCommune"."PCTerritoire_IdTerritoire",
    "ViewNuancePolitique"."NP_IdNuancePolitique",
    "ViewNuancePolitique"."NuancePolitique",
    "Profession"."CodeProfession",
    "Profession"."LibelleProfession"
   FROM "BREF"."Individu"
     JOIN "BREF"."Mandat" ON "Individu"."IdIndividu"::text = "Mandat"."Elu_IdIndividu"::text
     JOIN "BREF"."TypeMandat" ON "Mandat"."TypeDuMandat_IdTypeMandat" = "TypeMandat"."IdTypeMandat"
     JOIN "BREF"."ViewFonction" ON "Mandat"."IdMandat" = "ViewFonction"."Fonction_IdMandat"
     JOIN "BREF"."TypeFonction" ON "ViewFonction"."TypeDeFonction_IdTypeFonction" = "TypeFonction"."IdTypeFonction"
     JOIN "BREF"."Territoire" ON "Mandat"."Territoire_IdTerritoire"::text = "Territoire"."IdTerritoire"::text
     JOIN "BREF"."Inclusion" ON "Territoire"."IdTerritoire"::text = "Inclusion"."TerritoireInclu_IdTerritoire"::text
     JOIN "BREF"."ViewPopulationCommune" ON "Territoire"."IdTerritoire"::text = "ViewPopulationCommune"."PCTerritoire_IdTerritoire"::text
     JOIN "BREF"."ViewNuancePolitique" ON "Mandat"."IdNuancePolitique" = "ViewNuancePolitique"."NP_IdNuancePolitique"
     JOIN "BREF"."Profession" ON "Mandat"."IdProfession" = "Profession"."CodeProfession";